### ISSUE TITLE
оптимизация админки модуля

### ISSUE THREAD

**Issue by tcse** [dle-modules/DLE-Components#8]
Павел, предлагаю подумать о возможно интеграции админки в стандартный интерфейс самого DLE.

Так как наличие стандартной боковой панели с быстрыми ссылками по любым разделам DLE со временем оказалось очень даже удобным.
А полностью свой дизайн модуля заставляет делать лишние переходы.

пример скриншота  [http://online.tcse-cms.com/skitch/dle_Components_admin.jpg](url)

**Comment by pafnuty** [comment]
Однозначно не будет т.к. 
1. Интерфейс админки DLE написан на php-html-js-лапше, это очень сильно раздражает.
2. Вписать сложны функционал в интерфейс DLE довольно проблематично.
3. Делать как на скриншоте - лучше вообще никак не делать т.к. по сути мне нужно при разработке html и css кода учитывать ещё и бутстрап и js от админки DLE. 
Бутстрап я не люблю за развесистость ненужного кода.
4. Свою админку поддерживать проще.
5. Своя админка работет быстрее, особенно учитывая, что тут нормальный шаблонизатор, а не п.1.
